CREATE TABLE IF NOT EXISTS public.dm_analise_estoque (
    id_produto INTEGER PRIMARY KEY,
    codigo_produto TEXT,
    nome_produto TEXT,
    tem_venda BOOLEAN,
    estoque_atual INTEGER,
    demanda_media_dia NUMERIC,
    desvio_padrao_dia NUMERIC,
    demanda_total NUMERIC,
    dias_no_periodo INTEGER,
    primeira_data DATE,
    ultima_data DATE,
    demanda_leadtime NUMERIC,
    estoque_seguranca NUMERIC,
    rop NUMERIC,
    quantidade_sugerida INTEGER,
    cobertura_atual_dias NUMERIC,
    estoque_alvo NUMERIC,
    status TEXT,
    prioridade INTEGER,
    preco_venda NUMERIC,
    custo NUMERIC,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
