-- Add campaign_data column to store full strategy JSON
alter table campanhas_marketing 
add column if not exists campaign_data jsonb;

-- Comment on column
comment on column campanhas_marketing.campaign_data is 'Stores the full CampaignStrategy JSON object generated by AI';
