-- Add columns to campanhas_marketing table
-- Ensuring both campaign_data and analise_dados exist

ALTER TABLE campanhas_marketing 
ADD COLUMN IF NOT EXISTS campaign_data JSONB;

ALTER TABLE campanhas_marketing 
ADD COLUMN IF NOT EXISTS analise_dados JSONB;

COMMENT ON COLUMN campanhas_marketing.campaign_data IS 'Stores the full structured campaign strategy (report, dissemination, channels, etc) generated by Gemini';
COMMENT ON COLUMN campanhas_marketing.analise_dados IS 'Legacy/Compatibility column for report analysis';
